### ISSUE TITLE
Multiple "Vault Locked" Notifications after locking desktop

### ISSUE THREAD

**Issue by LSeelig** [quexten/goldwarden#102]
I get some number (2-4, typically) of notifications when my vault is locked, at least by locking my desktop (super + L). ![image](https://github.com/quexten/goldwarden/assets/37001137/92756f73-e22c-48f6-a984-1aaa0dd25d5b)

**Comment by LSeelig** [comment]
I am running the newest rpm (0.2.10) on Fedora 39 with GNOME 45.

**Comment by quexten** [comment]
Should be fixed on latest master build already, but I'll keep the issue open until 0.2.11.

**Comment by quexten** [comment]
Just released v0.2.12 but it seems this is not fixed just yet.

**Comment by LSeelig** [comment]
Well, I haven't seen it duplicate yet, but it is random, so I don't know if it is fixed for me or not.

**Comment by quexten** [comment]
Since there are no more reports here and I have not encountered this, closing for now. Please re-open if it re-occurs.
