### ISSUE TITLE
"Could not sync" Notification after logging into vault

### ISSUE THREAD

**Issue by LSeelig** [quexten/goldwarden#103]
Whenever I log in (with my pin), I immediately get a "Could not sync" notification. My vault status seems to indicate it is in fact synced. I am running the newest rpm (0.2.10) on Fedora 39 with GNOME 45.

**Comment by quexten** [comment]
Hm, this was a bug I really thought I had fixed in https://github.com/quexten/goldwarden/commit/61d490d5a0ab821693d3d4fcba1a7900f8026c09 (and it doesn't happen on my Fedora 39 system anymore). Do you happen to have any logs from the daemon for this?

**Comment by LSeelig** [comment]
I don't have this happening since I updated to 0.2.12, but I don't know if it's gone or just random.
