### ISSUE TITLE
Debian package not include ui

### ISSUE THREAD

**Issue by Mte90** [quexten/goldwarden#106]
So on https://github.com/quexten/goldwarden/wiki/System%E2%80%90wide-Autotype is mentioned to run the ui, this should include stuff from https://github.com/quexten/goldwarden/blob/main/ui/com.quexten.Goldwarden.desktop but the debian package doesn't have this content.

IF the ui it isn't shipped with the binary (as I can see the release is just that) the readme should explain to download and run the UI.

**Comment by quexten** [comment]
The only currently supported way of installing the UI is flatpak. I don't use debian, but it seems Flatpaks are not an issue on Debian and just require [a few commands ](https://www.linuxcapable.com/how-to-install-flatpak-on-debian-linux/) to enable.

**Comment by quexten** [comment]
Added a large banner at the top of  https://github.com/quexten/goldwarden/wiki/System%E2%80%90wide-Autotype .

(You can technically run the UI without Flatpak of course, but I'd rather not have to manage autostart / desktop files / dependencies / etc. for a variety of distros, so Flatpak is the only supported method)

**Comment by Mte90** [comment]
I understand the trouble, I am trying to see how to run it by the repository folder the ui.
Right now I just see that the `main.py` doesn't have the execution permission.

**Comment by Mte90** [comment]
On debian to run are required various packages for GTK:

```apt install python3-gi gobject-introspection gir1.2-gtk-4.0 gir1.2-adw-1```
