### ISSUE TITLE
Don't hardcode flatpak commands in GUI dialogs

### ISSUE THREAD

**Issue by SuperSandro2000** [quexten/goldwarden#134]
I am currently packaging goldwarden for NixOS. One of the problems I have encountered is that the GUI hardcodes ``flatpak run`` which obviously can't work when running outside of flatpak. To make goldwarden easier to package, this should be done smarter, ideally goldwarden should just run goldwarden and the rest is up to the packaging

eg https://github.com/quexten/goldwarden/blob/main/gui/src/gui/browserbiometrics.py#L45 or https://github.com/quexten/goldwarden/blob/main/gui/src/gui/ssh.py#L44

**Comment by quexten** [comment]
Very cool initiative!

I guess we can move these to some kind of resource files (maybe just a JSON file with help command strings is enough?).

**Comment by quexten** [comment]
#191 Implemented this by moving the commands to a resource.json file that can be overridden by the packaging distribution.
