### ISSUE TITLE
Port GTK4 python-defined UI to blueprints

### ISSUE THREAD

**Issue by quexten** [quexten/goldwarden#146]

**Comment by quexten** [comment]
#124

**Comment by jangernert** [comment]
Its worth looking into "blueprint" first. Its a nicer, less verbose syntax. Almost all new Gtk/Adwaita apps are using it.

https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/

**Comment by quexten** [comment]
Thanks for the info! I played around with writing the .ui files in another project of mine, which is already significantly better than the ad-hoc python spaghetti that's in-use right now. If blueprint-complier makes this even nicer, i'll definitely look into it.
