### ISSUE TITLE
Auto-approve credential access

### ISSUE THREAD

**Issue by benji78** [quexten/goldwarden#148]
I finally figure out how to get polkit to ask for my fingerprint as the `polkit-1` config file was moved from `/etc/pam.d/` to `/usr/lib/pam.d/`.
However I still have the annoying pinentry _approve credential access_ prompt which I need to accept through left-arrow enter. Entering a pin in Bitwarden is probably faster than clicking the four buttons scattered around my keyboard in order to open the extension, give my fingerprint and validate the pinentry prompt.

Can I somehow auto accept this prompt or is it something that is not recommended?

**Comment by quexten** [comment]
> I finally figure out how to get polkit to ask for my fingerprint as the polkit-1 config file was moved from /etc/pam.d/ to /usr/lib/pam.d/.

Is this something we need to adjust in the setup? If so which distro are you on?

Also, are you on the cli/daemon version, or on Flatpak? Recently, a lot of the double prompts got reduced, but not all are gone just yet.

**Comment by quexten** [comment]
Is this for unlocking the browser extension specifically?

**Comment by benji78** [comment]
This is indeed a duplicate, I searched for "pinentry" and "approve credential access" and didn't find it.

As for polkit, I'm on Arch using the CLI, but I am not sure this should be part of the setup. I do know however that I expected it to be in the [Wiki](../wiki/Browser-Biometric-Approval) which I have read quite a few times.
