### ISSUE TITLE
Cannot setup browserbiometrics with v0.2.14

### ISSUE THREAD

**Issue by mirenradia** [quexten/goldwarden#175]
After upgrading to v0.2.14, I can no longer set up browser biometrics.

## System information

OS: Fedora Linux 39
Desktop Environment: KDE Plasma 5.27.11
Browsers: Firefox 125.0.2 (RPM), Brave 124.1.65.123 (RPM), Chromium 123.0.6367.60 (Fedora Project RPM)
Goldwarden Version: 0.2.14 (EL7 RPM)

## Steps to reproduce

1. Run
   ```
   goldwarden setup browserbiometrics
   ```

## Result

I get the following output:

```
Native messaging host directory already exists: /home/miren/.config/google-chrome/NativeMessagingHosts/
Native messaging host directory already exists: /home/miren/.config/chromium/NativeMessagingHosts/
Native messaging host directory already exists: /home/miren/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/
Native messaging host directory already exists: /home/miren/.mozilla/native-messaging-hosts/
Found chrome-like browser: /home/miren/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts
Removing old manifest and proxy script
Error: chown /home/miren/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/com.8bit.bitwarden.json: operation not permitted
```

## Expected result

It sets up correctly and I don't get an error.

## Things I have tried

* Removing the file `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/com/8bit.bitwarden.json` before running.
* Removing the directory `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/` before running.

## Possible cause

Why do all of the `os.Chown` function calls pass `7` to the `uid` and `gid` arguments (e.g. [browserbiometrics/main.go:L129](https://github.com/quexten/goldwarden/blob/3ee8c722ef99e142ad35dfa7a016ce893f7c0748/browserbiometrics/main.go#L129))? Is this value special? My `uid` and `gid` on my system is `1000`.

I guess this might not have been a problem before because there was no error handling here as introduced by #140.

**Comment by quexten** [comment]
Not sure what happened there during some refactor. Fixed in #176
