### ISSUE TITLE
Upstream extension disabled biometrics on Linux

### ISSUE THREAD

**Issue by mirenradia** [quexten/goldwarden#183]
I know this isn't really an issue with this application per se but have Bitwarden disabled the biometrics unlock option in their browser extension? I can't see the option anymore (Bitwarden extension v2024.4.1) on Firefox v125.0.2 or Brave v124.1.65.123 running on Fedora 40 KDE. I had a look on Microsoft Edge on Windows 11 and the option is still there (even though I haven't installed any desktop application there).

The browser biometrics unlock is the main reason I started using goldwarden.

If this is the case, is there a way to get around this?

**Comment by quexten** [comment]
https://github.com/bitwarden/clients/blob/6365dcdc43b6b0df3c76c580ea0b61974dd97622/apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts#L272-L278

Not sure how to handle this yet....

**Comment by quexten** [comment]
We either have to somehow get upstream to revert that change / consider custom Linux setups (goldwarden or people building https://github.com/bitwarden/clients/pull/4586 locally), or provide a script to inject into the browser extension once for setup (rather cumbersome).

Unlocking still works fine after #185 is merged.

**Comment by quexten** [comment]
Opening the extension in a debugger and injecting:

`bitwardenMain.biometricStateService.setBiometricUnlockEnabled(true)
bitwardenMain.biometricStateService.setFingerprintValidated(false)`

into the console should get everything set up correctly. Not the best solution but hotfix for now. I'm not sure what the detailed steps on Brave are, but I'll add this in the wiki, until I have time to discuss with upstream browser extension.

**Comment by quexten** [comment]
@mirenradia In case your setup is broken, the steps to re-enable for Firefox/chromium are now noted here:

https://github.com/quexten/goldwarden/wiki/Browser-Biometric-Approval#firefox

**Comment by mirenradia** [comment]
Thanks for all the suggestions. I will give them a go once you have made a new release.

**Comment by mirenradia** [comment]
The instructions work for me. Thanks for the quick workaround!

**Comment by DigitallyRefined** [comment]
I also had to allow the extension to access native messaging:

**Chromium based browsers**

1. Manage extensions
2. Enable Developer mode
3. Click inspect background next to Bitwarden
4. In the console run:

```js
chrome.permissions.request({ permissions: ["nativeMessaging"] });
```

5. Switch back to the main browser window and click the "Allow" in the prompt

**Firefox based browsers**

1. Manage extensions
5. Click Bitwarden
6. Permissions 
7. Enable "Exchange messages with programs other than Firefox"

**Optionally enable "Ask for biometrics on launch"**

```js
bitwardenMain.biometricStateService.setPromptAutomatically(true);
```

**Comment by quexten** [comment]
@DigitallyRefined Nice catch! Added the steps to the wiki: https://github.com/quexten/goldwarden/wiki/Browser-Biometric-Approval
