### ISSUE TITLE
Login on official instance (EU) does not work. 

### ISSUE THREAD

**Issue by McBaumwolle** [quexten/goldwarden#190]
After reading some other issues and trying some things, I am out of ideas. As I signed up on vault.bitwarden.eu I used the following link to get the urls: 

https://vault.bitwarden.eu/api/config

But [setting](https://vault.bitwarden.eu/api/config) that up did now work, it returned: 

```
$ flatpak run --command=/app/bin/goldwarden com.quexten.Goldwarden vault login --email mail@mail.net
Login failed: Could not login: could not pre-login: Not Found: 
```

The normal login (via GUI) opens a popup to enter the password but also does not work, on the first try it gave an error with HTML code, but I can't reproduce this. Login via client id and secret did not work as well. 

I'd appreciate any help!

**Comment by quexten** [comment]
Can you post the output of `flatpak run --command=/app/bin/goldwarden com.quexten.Goldwarden config get-environment`?

**Comment by McBaumwolle** [comment]
Of course, hold on. 

```
$ flatpak run --command=/app/bin/goldwarden com.quexten.Goldwarden config get-environment
{"api":"https://vault.bitwarden.com/api","identity":"https://vault.bitwarden.com/identity","notifications":"https://notifications.bitwarden.com","vault":"https://vault.bitwarden.com"}
```

This was after a clean install, then I got the error message

```
Could not login via password: Bad Request:
{"message":"Traffic from your network looks unusual.
Connect to a different network or try again later. [Error Code 7]"}
```

so I tried the [id/secret](https://github.com/quexten/goldwarden/wiki/Getting-Started#unusual-traffic) thing again. 

```
$ flatpak run --command=/app/bin/goldwarden com.quexten.Goldwarden config set-api-url https://api.bitwarden.eu/
Done
$ flatpak run --command=/app/bin/goldwarden com.quexten.Goldwarden config set-identity-url https://identity.bitwarden.eu/
Done
8:~$ flatpak run --command=/app/bin/goldwarden com.quexten.Goldwarden config set-notifications-url https://notifications.bitwarden.eu/
Done
```

Then I got the ```Could not pre-login: Not Found:``` again.

**Comment by quexten** [comment]
With vault.bitwarden.eu this worked in the latest main branch version for me. I think the bug is most likely just the client id / client secret, which should be fixed in #212

**Comment by quexten** [comment]
Oh... my bad. Fix incoming soon, actually it was never updating the url properly when setting from the GUI.

**Comment by quexten** [comment]
0.3.2 is out now, should be on FlatHub within a few hours. Please try again there.

**Comment by McBaumwolle** [comment]
Thank you! Will try asap.

**Comment by McBaumwolle** [comment]
Works perfect now, thanks!
