### ISSUE TITLE
Running Gui without flatpak (unsandboxed)

### ISSUE THREAD

**Issue by Mte90** [quexten/goldwarden#202]
As usual I was trying the latest version for my ticket and running the UI and I got this running from source as `/home/mte90/Desktop/kde/goldwarden/gui/goldwarden_ui_main.py`:

```
starting goldwarden daemon /usr/bin/goldwarden
running locked status daemon
[INF] [10:40] [Goldwarden > Keyring] >>> Creating new memguard keyring
[INF] [10:40] [Goldwarden > Agent] >>> Agent listening on /home/mte90/.goldwarden.sock...
[WRN] [10:40] [Goldwarden > Agent] >>> Could not monitor idle: The name org.gnome.Mutter.IdleMonitor was not provided by any .service files
[INF] [10:40] [Goldwarden > SSH] >>> SSH Agent listening on /home/mte90/.goldwarden-ssh-agent.sock
listening for pinentry /usr/bin/goldwarden
[INF] [10:40] [Goldwarden > Agent] >>> Received pinentry registration request
[INF] [10:40] [Goldwarden > Agent] >>> Pinentry registration success: true
Traceback (most recent call last):
  File "/home/mte90/Desktop/kde/goldwarden/gui/src/gui/settings.py", line 30, in on_activate
    self.load()
  File "/home/mte90/Desktop/kde/goldwarden/gui/src/gui/settings.py", line 36, in load
    builder = load_template("settings.ui")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mte90/Desktop/kde/goldwarden/gui/src/gui/resource_loader.py", line 10, in load_template
    builder.add_from_file(pathprefix + ".templates/" + path)
gi.repository.GLib.GError: g-file-error-quark: Apertura del file «./src/gui/.templates/settings.ui» non riuscita: File or directory not exist (4)
create authenticated connection
[INF] [10:40] [Goldwarden > Agent] >>> Verified: true
```

**Comment by quexten** [comment]
Which path did you run this in?

**Comment by quexten** [comment]
![image](https://github.com/quexten/goldwarden/assets/11866552/cfa2c1ca-81b9-43ee-bf21-83a10ac6bdf7)
Should launch like this without flatpak

**Comment by quexten** [comment]
Ohh, I get it. The blueprints need to be compiled.
@Mte90 can you clone git@ssh.gitlab.gnome.org:jwestman/blueprint-compiler.git to your projects directory (f.e /home/mte90/projects/blueprint-compiler), then in [...]goldwarden/gui/src/gui/ run:  `/home/mte90/projects/blueprint-compiler/blueprint-compiler.py batch-compile .templates ./ ./*.blp`

**Comment by quexten** [comment]
This should convert the .blp files to .ui files, and you should be able to run it locally

**Comment by quexten** [comment]
Added this section to the wiki: https://github.com/quexten/goldwarden/wiki/Setting-up-the-Development-Environment#gui-unsandboxed

**Comment by Mte90** [comment]
Checked the Wiki, could be interesting a script to run to get a dev environment.
I know that I am the only not using the flatpak version but I need the gui with everything capable of running.

**Comment by quexten** [comment]
So did you try compiling the blueprints?
