### ISSUE TITLE
AUR Install Failing - cmd/version.txt No such file or directory

### ISSUE THREAD

**Issue by bjhuot** [quexten/goldwarden#205]
Installing latest version 0.3.1-1 (+3 0.54) from AUR via yay results in the above error from line 27 in the PKGBUILD. I was able to rectify it by altering the PKGBUILD to cli/cmd/version.txt and building manually, but then needed to run setup commands referencing /usr/bin/goldwarden rather than goldwarden.

After getting past polkit and systemd setup, works as normal.

**Comment by quexten** [comment]
Seen this report on the AUR too but didn't have time to get back to it yet. Will fix soon.
