### ISSUE TITLE
Windows - fido2.dll missing

### ISSUE THREAD

**Issue by akoray420** [quexten/goldwarden#207]
![image](https://github.com/quexten/goldwarden/assets/53649488/8aca9229-c12a-495d-b2b7-38834f690f68)

Fresh install on windows, but getting fido2.dll is missing error.

**Comment by akoray420** [comment]
Find original issue!

**Comment by tomitomas** [comment]
> Find original issue!

what was it ?? 
how do you fix it ?

**Comment by akoray420** [comment]
https://github.com/quexten/goldwarden/issues/139#issuecomment-2001143987
Check the owner's response
