### ISSUE TITLE
Error on autotype with Flatpak app on Ubuntu - ModuleNotFoundError: No module named 'Xlib'

### ISSUE THREAD

**Issue by MurzNN** [quexten/goldwarden#210]
When I'm trying to make autotype on the goldwaren installed from Flatpak, I get an error in the console:
```
/app/bin/src/gui/quickaccess.py:159: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  action_row.set_icon_name("dialog-password")
/app/bin/src/gui/quickaccess.py:113: DeprecationWarning: Gtk.Widget.hide is deprecated
  self.window.hide()
Exception in thread Thread-2 (perform_autotype):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/src/gui/quickaccess.py", line 115, in perform_autotype
    autotype.autotype(text)
  File "/app/bin/src/services/autotype/autotype.py", line 12, in autotype
    from .x11autotype import type
  File "/app/bin/src/services/autotype/x11autotype.py", line 27, in <module>
    from Xlib.display import Display
ModuleNotFoundError: No module named 'Xlib'
```

Installing the xlib library locally like this:
```
$ sudo apt install python3-xlib
```
doesn't help, seems because Python checks it in the Flatpak namespace.

**Comment by quexten** [comment]
Hmm, weird:
https://github.com/quexten/goldwarden/blob/f869e9afffb8ddf9bfe6573f82405666957696b2/gui/python3-requirements.json#L20-L33

Gonna have to do some tests on an xorg system for this.

**Comment by quexten** [comment]
Oh, my bad. Seems it was not added on the FlatHub python3-requirements.json. Should be an easy fix.

**Comment by quexten** [comment]
Should be fixed on next release.

**Comment by quexten** [comment]
0.3.2 is out now, should be on FlatHub within a few hours. Please try again there.

**Comment by MurzNN** [comment]
Confirm, now autotype working well on Flatpak with KDE on Ubuntu 23.10 Linux, thanks!
