### ISSUE TITLE
Flatpak version crash after pin enter

### ISSUE THREAD

**Issue by KweezyCode** [quexten/goldwarden#216]
   ~  flatpak run com.quexten.Goldwarden                                                                                                                                 ✔ 
F: X11 socket /tmp/.X11-unix/X0 does not exist in filesystem, trying to use abstract socket instead.
starting goldwarden daemon /app/bin/goldwarden
running locked status daemon
[INF] [23:35] [Goldwarden > Keyring] >>> Creating new memguard keyring
[WRN] [23:35] [Goldwarden > Agent] >>> Config is not locked. SET A PIN!!
[INF] [23:35] [Goldwarden > Agent] >>> Agent listening on /home/kweezy/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...
[INF] [23:35] [Goldwarden > SSH] >>> SSH Agent listening on /home/kweezy/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock
[WRN] [23:35] [Goldwarden > Agent] >>> Could not monitor idle: org.freedesktop.DBus.Error.ServiceUnknown
listening for pinentry /app/bin/goldwarden
Running in flatpak, registering with background portal for autostart.
[INF] [23:35] [Goldwarden > Agent] >>> Received pinentry registration request
[INF] [23:35] [Goldwarden > Agent] >>> Pinentry registration success: true
create authenticated connection
[INF] [23:35] [Goldwarden > Agent] >>> Verified: true
[INF] [23:36] [Goldwarden > Pinentry] >>> Asking for pin |Pin Change|Enter your desired pin|
[INF] [23:36] [Goldwarden > Agent] >>> Received getPassword request
zsh: terminated  flatpak run com.quexten.Goldwarden
    ~ 

**Comment by quexten** [comment]
Hmm, what's your distro, desktop-environment and do you use wayland or xorg?

**Comment by KweezyCode** [comment]
Manjaro KDE, xorg. The bug disappeared after a reboot, so i am closing issue
