### ISSUE TITLE
Bad CPU type

### ISSUE THREAD

**Issue by Imzxhir** [quexten/goldwarden#221]
Description: I tried to run the x86_64 version of goldwarden on macOS, but I kept getting an error message that said `exec: Failed to execute process '/usr/local/bin/goldwarden': Bad CPU type in executable.`, even though I have an intel iMac.

**Comment by quexten** [comment]
`goldwarden_macos_x86_64: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>` Seems like the CI pipeline somehow ran on arm64.

**Comment by augustozanellato** [comment]
> `goldwarden_macos_x86_64: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>` Seems like the CI pipeline somehow ran on arm64.

It appears that `macos-latest` switched to being arm64 by default. Go should probably be configured to crossbuild to amd64.

**Comment by quexten** [comment]
Updated this to `macos-13` in the pipeline. Switching to cross-compliation will likely lead to disabling fido2 support. I tried enabling cross-compilation of the C lib with the zig compiler too, but failed to achieve this. So until mac x86 runners are EOL, I'd prefer to keep the builds on them.

**Comment by quexten** [comment]
Should be fixed on 0.3.3
