### ISSUE TITLE
vault set pin error (Mac Intel)

### ISSUE THREAD

**Issue by Stefanoz45** [quexten/goldwarden#224]
Hi, 

I'm getting this error when i run `goldwarden vault pin set` on my mac (intel):

`Pin updating failed: GETPIN response didn't start with D; got "S ERROR curses.isatty 83918950 "`

**Comment by quexten** [comment]
Fixed in #228

**Comment by quexten** [comment]
Please try again on `v0.3.3` (with pinentry-mac installed)
