### ISSUE TITLE
[Feature request] Implement the freedesktop.org Secret Service

### ISSUE THREAD

**Issue by bb010g** [quexten/goldwarden#254]
Goldwarden could implement the [freedesktop.org Secret Service API](<https://specifications.freedesktop.org/secret-service/latest/>), similar to how it already implements an SSH agent. If you'd like to see how this looks in a password manager, KeePassXC also implements the Secret Service.

You'll additionally want to implement [`org.freedesktop.impl.portal.Secret`](<https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.impl.portal.Secret.html>) to support usage through Flatpak (see <https://github.com/flatpak/xdg-desktop-portal/issues/970#issuecomment-1438351750>).

This would be pretty handy for desktop environments that don't already have GNOME Keyring or KDE Wallet.

**Comment by quexten** [comment]
Thanks for the feature request. This is actually a duplicate to https://github.com/quexten/goldwarden/issues/9 . Just like in that issue, is there specific secrets that would benefit from being synced? So far most things I've encountered for libsecret have local relevance to just that system only, and don't really go well in Bitwarden?

I'd be interested to find a use-case for a specific app here.

**Comment by bb010g** [comment]
> This is actually a duplicate to #9 .

Extremely sorry about missing that and filing a duplicate. I'll go move over to there. (I've reacted to that issue before; maybe I misread or misremembered it as something other than implementing the Secret Service, since "support" is more generic. Or I might have just been searching for "freedesktop".)
