### ISSUE TITLE
Cannot login with YubiKey (on Vaultwarden)

### ISSUE THREAD

**Issue by cromefire** [quexten/goldwarden#266]
I'm trying to use this with vaultwarden, which should be pretty compatible. Every time I try to login though, it asks for my password and then fails with: `Login failed: Could not login: could not obtain two-factor auth token: no second factor available` and no other error.

When I setup TOTP, everything works.

**Comment by cromefire** [comment]
I also tried to setup the external daemon thing, but it seems to be overwritten by the flatpak I think and I haven't found any option to just completely disable starting the daemon in the sandbox, other than just killing it manually after the start, maybe that should any option and documented on the respective wiki page.

**Comment by quexten** [comment]
I think external daemon docs should probably be removed at this point as it is untested. The following is also untested, but will probably work: `flatpak run --device=all com.quexten.Goldwarden` in order to give access to the yubikey / fido2 key.

**Comment by cromefire** [comment]
The trick why I had all the problems was that the settings of flatseal don't work on autostart and you have to edit `.config/autostart/com.quexten.Goldwarden.desktop` with for the flatpak to work. Maybe that's worth documenting.

When using normal `flatpack run` even without the parameter it seemed to work using flatseal. Weird that there's this distinction.
