### ISSUE TITLE
`goldwarden.service` doesn't start every time I turn on my computer.

### ISSUE THREAD

**Issue by ruizlenato** [quexten/goldwarden#312]
```
~ ➜ systemctl --user status goldwarden
○ goldwarden.service - "Goldwarden daemon"
     Loaded: loaded (/home/renato/.config/systemd/user/goldwarden.service; enabled; preset: enabled)
     Active: inactive (dead)
```

For the service to work, I have to restart it.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the goldwarden.service file to ensure it starts properly after login. Added Type=simple and Restart=on-failure to make the service more robust.

You can review changes in this commit: https://github.com/mark-addams001881/quexten-goldwarden-312/commit/5c03fa4757f5bc5a3b62b5dd604e6c7ff3489fc1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ruizlenato** [comment]
I don't understand why but I created a service called `test` and tried to run goldwarden, it worked, then I tried to copy everything that was in the original goldwarden service to this service test and it also worked. In the end I deleted the service file and created a new one with the same name and it just worked.
