### ISSUE TITLE
system-wide autotype does not work

### ISSUE THREAD

**Issue by zany130** [quexten/goldwarden#34]
Installed goldwarden from the AUR

following https://github.com/quexten/goldwarden/wiki/System%E2%80%90wide-Autotype

I cant get `dbus-send --type=method_call --dest=com.quexten.Goldwarden.autofill /com/quexten/Goldwarden com.quexten.Goldwarden.Autofill.autofill`

tested trying to get my password for google  with `goldwarden logins get www.google.com` and that works so Goldwarden seems to be accessing my bitwarden account fine
```
systemctl --user status goldwarden.service
● goldwarden.service - "Goldwarden daemon"
     Loaded: loaded (/home/zany130/.config/systemd/user/goldwarden.service; enabled; preset: enabled)
     Active: active (running) since Thu 2023-12-28 19:22:22 EST; 1min 24s ago
   Main PID: 796781 (goldwarden)
      Tasks: 17 (limit: 38363)
     Memory: 80.4M (peak: 2.0G)
        CPU: 7.039s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/goldwarden.service
             └─796781 /usr/bin/goldwarden daemonize

Dec 28 19:23:30 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Keyring] >>> Unlocking keyring with account key
Dec 28 19:23:30 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Bitwarden API] >>> Clearing vault...
Dec 28 19:23:30 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Bitwarden API] >>> Adding 560 ciphers to vault...
Dec 28 19:23:30 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Systemauth] >>> Checking permission for goldwarden with session type com.quexten.goldwarden.accessvault
Dec 28 19:23:30 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Systemauth] >>> Permission granted from cached session
Dec 28 19:23:30 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Pinentry] >>> Asking for approval |Approve Credential Access|zany130 on alacritty>fish>goldwarden is trying to access credentials for u>
Dec 28 19:23:30 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Websocket] >>> Connected to websocket server...
Dec 28 19:23:33 Garuda-Linux goldwarden[796781]: [WRN] [19:23] [Goldwarden > Websocket] >>> Invalid message received, length too short
Dec 28 19:23:33 Garuda-Linux goldwarden[796781]: [INF] [19:23] [Goldwarden > Pinentry] >>> Got approval from user
Dec 28 19:23:39 Garuda-Linux goldwarden[796781]: [WRN] [19:23] [Goldwarden > Websocket] >>> Invalid message received, length too short
```

**Comment by quexten** [comment]
Thanks for reporting the issue. Autotype is currently only available when running the Flatpak (or by running the python ui manually). The daemon does not need to run in the Flatkpak, so running as a systemd service is fine, but you do need to have have the Flatpak (or just the ui/main.py) running in some way. I'm working to get the Flatpak published on Flathub to make installation easier, but in the meantime you can find the latest Flatpak build here:
https://github.com/quexten/goldwarden/actions/runs/7352949205

I have also updated the Wiki to inform about this.

(Also, beware that running outside of the Flatpak is not super well tested at the moment, so Flatpak is the easier route)

**Comment by zany130** [comment]
Ah ok, thanks I was using the AUR package (should have mentioned it) so the flatpak is the preferred method?

**Comment by quexten** [comment]
Since the flatpak/ui was only implemented last week or so, I haven't had time to think about how to distribute it yet. On the one hand, many users might prefer just having the single go binary without any further dependencies, on the other, installing the UI version from the AUR would also be nice. But then, different mechanisms for automatically starting on boot would have to be used. I'll think about this.

**Comment by zany130** [comment]
FWIW I tried getting the `main.py` under the ui folder working locally on my system but had issues trying to get the python deps installed. Specifically tendo, there doesn't seem to be an arch package for that.

So it may just be easier to just have it flat packed and the cli portion available through the aur.

that's what I am doing now didn't realize you can use both together
