### ISSUE TITLE
Commands on the Getting Started page appear to be out of date

### ISSUE THREAD

**Issue by Anthony-Fiddes** [quexten/goldwarden#36]
I noticed that the commands on the [Getting Started](https://github.com/quexten/goldwarden/wiki/Getting-Started) page do not properly reference the `vault` command.

E.g.:

* The page has `goldwarden set pin`, but the command that I had to use was `goldwarden vault pin set`.
* The page has `goldwarden login --email <email>`, but I had to use `goldwarden vault login --email <email>`

Installed version:

![image](https://github.com/quexten/goldwarden/assets/11233666/90e86fd4-9a7f-4b4a-905c-51c249ace25b)

**Comment by quexten** [comment]
Thanks a lot for the report, fixed it in the wiki now!

**Comment by Anthony-Fiddes** [comment]
Awesome, thanks!
