### ISSUE TITLE
Unlock fails due to pinentry in systemd service

### ISSUE THREAD

**Issue by zany130** [quexten/goldwarden#38]
while troubleshooting https://github.com/quexten/goldwarden/issues/35

I noticed I am unable to access my Bitwarden vault anymore.

```
goldwarden vault status
{
  "locked": false ,
  "loginEntries": 0 ,
  "noteEntries": 0 ,
  "lastSynced":	"1969-12-31 19:00:00 -0500 EST",
  "websocketConnected": false ,
  "pinSet": false ,
  "loggedIn": false
}
goldwarden vault login --email andresdortiz@gmail.com
Login failed: No pin set. Set a pin first!

 ╭─zany130@garuda in ~ via  v3.11.6 took 4ms
 ╰─λ goldwarden vault pin set
Pin updating failed: pinentry: unexpected response: "S ERROR gtk2.isatty 83918950 
```

```
pacman -Qi goldwarden
Name            : goldwarden
Version         : 0.2.6-1
```

```
flatpak info com.quexten.Goldwarden

Goldwarden - A Bitwarden compatible desktop client

          ID: com.quexten.Goldwarden
         Ref: app/com.quexten.Goldwarden/x86_64/test
        Arch: x86_64
      Branch: test
     Version: 0.2.5
     License: MIT
      Origin: goldwarden-origin
  Collection: org.flathub.Test.Build72997
Installation: user
   Installed: 9.5 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: 193d26166b1d679d17ae26799cbbb9ef5c4a6e636d3b48b6014505088386adb5
     Subject: Update com.quexten.Goldwarden.yml to v0.2.5 (2a8452e2)
        Date: 2023-12-28 22:31:43 +0000
    
    
```    

Operating System: Garuda Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.6.8-1-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

**Comment by Anthony-Fiddes** [comment]
I had the same problem just now. 

Try running `goldwarden daemonize` manually and seeing if the methods work in a new terminal session. That worked for me. To get it running properly in the background again I did `systemctl restart --user goldwarden.service`

**Comment by quexten** [comment]
Hm, so from the error output, it seems that the pinentry program is having issues. I previously had a similar bug when my systemd servicefile was missing: `Environment="DISPLAY=:0"` under the `[Service]` section. Just to make sure, is this still in your service file?

**Comment by zany130** [comment]
```
cat .config/systemd/user/goldwarden.service
File: .config/systemd/user/goldwarden.service
[Unit]
Description="Goldwarden daemon"

[Service]
ExecStart=/usr/bin/goldwarden daemonize
Environment="DISPLAY=:0"

[Install]
WantedBy=graphical-session.target
```


interestingly the status of the service is as follows
```
goldwarden.service - "Goldwarden daemon"
     Loaded: loaded (/home/zany130/.config/systemd/user/goldwarden.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-12-30 12:33:14 EST; 1h 23min ago
   Main PID: 5942 (goldwarden)
      Tasks: 16 (limit: 38363)
     Memory: 26.5M (peak: 33.9M swap: 2.8M swap peak: 3.1M)
        CPU: 519ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/goldwarden.service
             └─5942 /usr/bin/goldwarden daemonize

Dec 30 12:58:59 Garuda-Linux goldwarden[5942]: [INF] [12:58] [Goldwarden > Systemauth] >>> Checking permission for goldwarden with session type com.quexten.goldwarden.accessvault
Dec 30 12:58:59 Garuda-Linux goldwarden[5942]: [INF] [12:58] [Goldwarden > Biometrics] >>> Checking biometrics for com.quexten.goldwarden.accessvault
Dec 30 12:59:08 Garuda-Linux goldwarden[5942]: [INF] [12:59] [Goldwarden > Biometrics] >>> Biometrics result: true
Dec 30 12:59:08 Garuda-Linux goldwarden[5942]: [INF] [12:59] [Goldwarden > Systemauth] >>> Permission granted, creating session
Dec 30 12:59:08 Garuda-Linux goldwarden[5942]: [INF] [12:59] [Goldwarden > Pinentry] >>> Asking for pin |Pin Change|Enter your desired pin|
Dec 30 13:03:15 Garuda-Linux goldwarden[5942]: [INF] [13:03] [Goldwarden > Auth] >>> Refreshing token
Dec 30 13:03:15 Garuda-Linux goldwarden[5942]: Could not get refresh token:  chacha20poly1305: ciphertext too short
Dec 30 13:33:15 Garuda-Linux goldwarden[5942]: [WRN] [13:33] [Goldwarden > Agent] >>> Could not get token: chacha20poly1305: ciphertext too short
Dec 30 13:33:15 Garuda-Linux goldwarden[5942]: [INF] [13:33] [Goldwarden > Auth] >>> Refreshing token
Dec 30 13:33:15 Garuda-Linux goldwarden[5942]: Could not get refresh token:  chacha20poly1305: ciphertext too short
```

also forgot to mention I still have the flatpak installed for the GUI Ill updated OP with that

**Comment by zany130** [comment]
Somehow fixed it by running `goldwarden vault purge` and then restarting the systemd service with `systemctl --user restart goldwarden.service`

**Comment by quexten** [comment]
> also forgot to mention I still have the flatpak installed for the GUI Ill updated OP with that

That shouldn't interfere when using the CLI with a daemon running in the CLI.
> chacha20poly1305: ciphertext too short

This is interesting though, I think your config got corrupted some how.

**Comment by quexten** [comment]
Ah, you managed to fix the corrupted config by purging the vault. Nice.

**Comment by quexten** [comment]
So is everything working now on this issue (Can I close it)?

**Comment by zany130** [comment]
yup had the same thought don't know if that helps @Anthony-Fiddes  aswell though

working fine for me though

**Comment by quexten** [comment]
> just a FYI you might get a server error I guess from to many attempts or something. just tried a different network like the error message said and reset the systemd service then I was good to go

This is another issue (https://github.com/quexten/goldwarden/issues/33). Since I'm using a self-hosted installation I haven't gotten around to implement api-key support yet, but that's required to get around Bitwarden's brute-force/credential stuffing protection.

**Comment by Anthony-Fiddes** [comment]
@zany130 Yeah everything is working fine on my end. I also purged my vault, but I didn't realize it was a necessary step to resolve the issue.
