### ISSUE TITLE
Vault login results in "Traffic from your network looks unusual"

### ISSUE THREAD

**Issue by ThatOneCalculator** [quexten/goldwarden#43]
```
$ goldwarden vault login --email me@redacted.tld
Login failed: Could not login: could not pre-login: Bad Request: {"message":"Traffic from your network looks unusual. Connect to a different network or try again later. [Error Code 6]"}
```

I have no problems logging into the browser extension or anything else like that, nor have I ever seen a message like this from any other application.

**Comment by ThatOneCalculator** [comment]
Probably related to

- https://community.bitwarden.com/t/error-code-6-unusual-network-traffic/45987/17
- https://bitwarden.com/help/unusual-traffic-error/

Maybe it's *how* Goldwarden is doing the requests for the login?

**Comment by quexten** [comment]
Thanks for raising the issue! I mainly test on self-hosted, so I have not gotten to implementing https://github.com/quexten/goldwarden/issues/33 yet, but this is a common issue with 3rd party clients, and even the official CLI sometimes. The solution is to use an API key, but as mentioned, there is no support in goldwarden just yet, though it's on the top of my bucket list. Will post an update when it's implemented :)

**Comment by ThatOneCalculator** [comment]
Got it, thank you!

**Comment by quexten** [comment]
Did you build goldwarden yourself, or did you install a package? If you built it yourself, feel free to try the latest master branch and configure your API key with this guide:
https://github.com/quexten/goldwarden/wiki/Getting-Started#unusual-traffic

**Comment by ThatOneCalculator** [comment]
I did the AUR package for goldwarden, I'll try building from source now

**Comment by ThatOneCalculator** [comment]
`go install github.com/quexten/goldwarden@main` doesn't seem to actually install anything

**Comment by quexten** [comment]
> go install github.com/quexten/goldwarden@main doesn't seem to actually install anything

It installs the binary to your go bin path, i.e you would need to add ~/go/bin/ to your PATH variable

**Comment by ThatOneCalculator** [comment]
Interesting... I've installed stuff with go install before and it usually adds it to the path

**Comment by ThatOneCalculator** [comment]
before I could even get to that step, I got this error

```
❯ ~/go/bin/goldwarden setup polkit
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/mv /tmp/goldwarden-policy /us ... actions/com.quexten.goldwarden.policy' as the super user
Authenticating as: Kainoa Kanter (kainoa)
Password: 
==== AUTHENTICATION FAILED ====
panic: exit status 127

goroutine 1 [running]:
github.com/quexten/goldwarden/cmd.setupPolkit()
	/home/kainoa/go/pkg/mod/github.com/quexten/goldwarden@v0.2.8-0.20240104211310-f2fb11d16e2d/cmd/setup_linux.go:33 +0x40f
github.com/quexten/goldwarden/cmd.glob..func16(0xc0000ed200?, {0x90f65a?, 0x4?, 0x90f556?})
	/home/kainoa/go/pkg/mod/github.com/quexten/goldwarden@v0.2.8-0.20240104211310-f2fb11d16e2d/cmd/setup_linux.go:65 +0xf
github.com/spf13/cobra.(*Command).execute(0xc9f860, {0xd0a1a0, 0x0, 0x0})
	/home/kainoa/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xc9f2a0)
	/home/kainoa/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/kainoa/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cmd.Execute({0x0, 0x0, {0x0, 0x0}, 0x0, {0xc000034c00, 0x2f}, 0x0, 0x0, {0x0, ...}, ...})
	/home/kainoa/go/pkg/mod/github.com/quexten/goldwarden@v0.2.8-0.20240104211310-f2fb11d16e2d/cmd/root.go:35 +0x1ee
main.main()
	/home/kainoa/go/pkg/mod/github.com/quexten/goldwarden@v0.2.8-0.20240104211310-f2fb11d16e2d/main.go:83 +0x958
	```

**Comment by ThatOneCalculator** [comment]
There we go, it works now! How do you install the GUI from source?

**Comment by quexten** [comment]
> There we go, it works now! How do you install the GUI from source?

I released an updated flatpak, so that's the easiest way. You can use it in conjunction with a non-sandboxed daemon, or standalone. On arch, I believe it should be sufficient to install the flatpak package https://archlinux.org/packages/?name=flatpak and then installing the flatpak using `flatpak install`.

While it is possible to use the UI without sandboxing, it's very much untested, so I won't provide further instructions here. If you really want to do this, feel free to open a discussion under discussions, and we can figure something out.

Other than that, since this seems fixed by using API keys, I'm closing this issue report now. Thanks again for reporting.
