### ISSUE TITLE
Optional No-Pin Mode

### ISSUE THREAD

**Issue by quexten** [quexten/goldwarden#50]
In response to @mufeedali:

Polkit an the pin serve two different purposes (somewhat). Since we do *not* want to expose the vault to someone having access to the disk on boot (unencrypted main volume, etc), the pin is required to derive a key to decrypt the vault. If this were not the case, anyone with access to your (unencrypted) disk, or an unfortunate backup that captured the config, could access your vault.

Polkit only does authentication, no key derivation. Thus, it is only useful once the encryption key is already present in memory.

The two (not great) alternatives are: storing the key in libsecret - which makes the disk image unproblematic at least, but exposes the key to the user's other running processes. And alternatively, using no encryption, but this is just really not great, due to the mentioned attack above. *Maybe* I will introduce an environment variable such as `GOLDWARDEN_NO_PIN_THIS_EXPOSES_YOUR_VAULT_TO_YOUR_DISK=true`, so that way the user is aware of the risk.

_Originally posted by @quexten in https://github.com/quexten/goldwarden/discussions/46#discussioncomment-8026500_

**Comment by mufeedali** [comment]
What does "GOLDWARDEN_PIN_REQUIREMENT_DISABLED" do currently?

**Comment by LSeelig** [comment]
To be clear, I am not well-educated on this. But don't DEs (at least KDE and Gnome) have a wallet/keyring that needs to be decrypted by the user with a typed password? Is it possible to unlock goldwarden with that instead? Wouldn't this prevent access on an unencrypted disk?

**Comment by quexten** [comment]
For the typical application (vscode, chrome) that works, but Goldwarden specifically does not use the keyring because it is accessible user-wide. The default threat-model includes malicious processes running under the same user, and the keyring would allow the other processes to access the same encryption key.

I've been contemplating adding an explicit configuration where user-wide access is permitted, and f.e the vault is locked user-wide when the system is idle, as long as the ramifications are clear to the user. But the default is a bit more restricted.

**Comment by quexten** [comment]
I guess I should write a wiki page about the threat model too.

**Comment by LSeelig** [comment]
> malicious processes running under the same user, and the keyring would allow the other processes to access the same encryption key.

Ah. Thank you for your response. Prior to your clarification, I was under the impression this was already possible, but I must have misread the page ([https://wiki.gnome.org/Projects/GnomeKeyring/SecurityPhilosophy](https://wiki.gnome.org/Projects/GnomeKeyring/SecurityPhilosophy)).

**Comment by quexten** [comment]
https://github.com/quexten/goldwarden/pull/113 this allows using system auth even when the vault was locked. The pin is only required on every boot once now. So other than that probably not implementing this unless there is a really good use case.
