### ISSUE TITLE
setup systemd fails

### ISSUE THREAD

**Issue by zany130** [quexten/goldwarden#6]
setting up systemd fails

```
goldwarden setup systemd
panic: exit status 1

goroutine 1 [running]:
github.com/quexten/goldwarden/cmd.setupSystemd()
	github.com/quexten/goldwarden/cmd/setup.go:83 +0x26b
github.com/quexten/goldwarden/cmd.glob..func12(0xc0000e7a00?, {0x564fa2040320?, 0x4?, 0x564fa204020e?})
	github.com/quexten/goldwarden/cmd/setup.go:94 +0xf
github.com/spf13/cobra.(*Command).execute(0x564fa26de400, {0x564fa294aaa0, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x564fa26ddb60)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/quexten/goldwarden/cmd.Execute({0x0, 0x0, {0x0, 0x0}, 0x0, {0xc00034eed0, 0x25}, 0x0, 0x0, {0x0, ...}, ...})
	github.com/quexten/goldwarden/cmd/root.go:35 +0x165
main.main()
	github.com/quexten/goldwarden/main.go:65 +0x578
	```
	this is built from the latest git

```

sys info

```
inxi -b
System:
  Host: Garuda-Linux Kernel: 6.5.2-273-tkg-bore-eevdf arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.7 Distro: Garuda Linux
Machine:
  Type: Desktop Mobo: ASRock model: X470 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P5.10 date: 10/20/2022
CPU:
  Info: 6-core AMD Ryzen 5 5600X [MT MCP] speed (MHz): avg: 4074
    min/max: 550/4651
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.2.0
    compositor: kwin_wayland driver: X: loaded: amdgpu
    unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu resolution:
    1: 2048x864 2: 1536x864 3: 1536x864
  API: OpenGL v: 4.6 Mesa 23.1.7-arch1.1 renderer: AMD Radeon RX 6700 XT
    (navi22 LLVM 16.0.6 DRM 3.54 6.5.2-273-tkg-bore-eevdf)
Network:
  Device-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
  Device-2: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 2.96 TiB used: 2.33 TiB (78.7%)
Info:
  Processes: 530 Uptime: 1h 30m Memory: total: 32 GiB available: 31.26 GiB
  used: 11.23 GiB (35.9%) Shell: fish inxi: 3.3.29
  ```

**Comment by quexten** [comment]
Thanks for the report on this as well. I'll investigate this and post updates when I found the issue.

**Comment by quexten** [comment]
Should be fixed on latest master.
I've also bumped the version to v0.1.6 (https://github.com/quexten/goldwarden/releases/tag/v0.1.6).

Feel free to re-open should the issue persist.
