### ISSUE TITLE
Support non-biometric auth

### ISSUE THREAD

**Issue by Atemu** [quexten/goldwarden#61]
For testing (and because my desktop doesn't have biometrics), I'd like to set a non-biometric pin (password would be good enough for my case) using `goldwarden vault pin set` but I get this log:

```
Jan 13 20:48:09 HEPHAISTOS .goldwarden-wrapped[1385378]: [INF] [20:48] [Goldwarden > Systemauth] >>> Checking permission for .goldwarden-wra with session type com.quexten.goldwarden.accessvault
Jan 13 20:48:09 HEPHAISTOS .goldwarden-wrapped[1385378]: [INF] [20:48] [Goldwarden > Biometrics] >>> Checking biometrics for com.quexten.goldwarden.accessvault
Jan 13 20:48:09 HEPHAISTOS .goldwarden-wrapped[1385378]: [INF] [20:48] [Goldwarden > Biometrics] >>> Biometrics result: false
```

Installed under NixOS 24.05 (polkit enabled)

**Comment by quexten** [comment]
Without biometrics, right now, normal polkit auth will be used, i.e your user account's password. Usually, it should fallback to the pin if somehow the polkit auth fails. In your case it seems to just deny it, I will look into it.

**Comment by quexten** [comment]
Should at least instead ask for pin in d2cd2da7e26df3b69a54d8035d3487a6b51613d6
Not sure why it's not working in the first place, but it removes the requirement of biometrics/systemauth on first pin.

**Comment by alexandru0-dev** [comment]
i have the same setup (nixos with polkit setup) tho i have biometrics but still have the same log (i'm on 2.10.0)

**Comment by quexten** [comment]
0.2.10 does include the patch, so this bug is still around. Thanks for the report.

**Comment by alexandru0-dev** [comment]
> 0.2.10 does include the patch, so this bug is still around. Thanks for the report.

Uh sorry I thought it updated the comment but apparently I forgot to confirm

UPDATE: it works, I just forgot to enable polkit-agent

I still have an issue where If I try to make it a systemd service where pinentry fails to execute as it's not available in path
