### ISSUE TITLE
Browser Biometrics: Forever Waiting Confirmation from Desktop

### ISSUE THREAD

**Issue by HauntedBunnies13** [quexten/goldwarden#62]
Hello,
I've recently started switching to Linux and I really want to make this work, because I really enjoy using biometrics for Bitwarden on Windows. I'm running Fedora 39, and I installed both the Goldwarden rpm and flatpak. My browser of choice is Vivaldi. I setup browserbiometrics via the commandline, and it seemed to have found Vivaldi. The Goldwarden GUI shows that the SSH and Goldwarden Daemons are both running, and "Login with device" shows "Waiting for requests" and "DBUS Service" shows "Listening". The Wiki seems to tell me to just turn on browser biometrics on the browser extension from here, but it shows "Waiting confirmation from desktop" without any indication that the desktop is trying to connect. I'm unsure what to do from here.

**Comment by alba4k** [comment]
Same over here..

**Comment by alba4k** [comment]
https://github.com/quexten/goldwarden/issues/37#issuecomment-1880189299

**Comment by alba4k** [comment]
@quexten

Is this intended behaviour? 
https://imgur.com/a/t3PyrKl

Not asking for polkit auth, just for my pin + some weird double confirmation dialog

**Comment by quexten** [comment]
No, it's a bug, thanks for reporting.

**Comment by quexten** [comment]
> ,

@HauntedBunnies13 , for your problem specifically, could you let me know, what is your `GOLDWARDEN_SOCKET_PATH` set to?

**Comment by HauntedBunnies13** [comment]
@quexten I realized after I made the issue that my problem was likely related to the environment variables, which I hadn't set according to the wiki, but I couldn't figure out where I would put the environment variables (I'm new to Linux, and haven't dealt with environment variables before).

Unfortunately, I had too many issues getting Linux set up how I want it and not enough time to troubleshoot it at the moment, so I've switched back to Windows and removed Linux from my machine.

**Comment by quexten** [comment]
Thanks for the info. Still, the environment variables having to be configured for basic functionality isn't ideal. I'll look into changing this in the future to auto-detect configuration.
