### ISSUE TITLE
Flatpak unable to access account

### ISSUE THREAD

**Issue by zany130** [quexten/goldwarden#63]
It used to be that the Flatpak would detect my account from the system installed in Goldewarden. However, it is no longer doing this.

Furthermore, I can't even log in using the flatpak as I get stuck in this window and the login button does nothing

![image](https://github.com/quexten/goldwarden/assets/25832539/5999b193-a11e-46a1-82c9-be4fdfecf6e3)

System goldwarden (AUR)
```
Name            : goldwarden
Version         : 0.2.9-1
```

Flatpak
```
Goldwarden          com.quexten.Goldwarden        0.2.9            stable       flathub     user
```

System
```
Operating System: Garuda Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.7.0-3-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
```

**Comment by quexten** [comment]
Thanks for reporting, what is your $GOLDWARDEN_SOCKET_PATH set to?

**Comment by zany130** [comment]
> Thanks for reporting, what is your $GOLDWARDEN_SOCKET_PATH set to?
```
[zany130@Garuda-Linux ~]$ echo $GOLDWARDEN_SOCKET_PATH

[zany130@Garuda-Linux ~]$
 ```
 seems it is not set could be my issue, and I just saw this on the flatpak wiki page 

> Goldwarden is available as a graphical application as a Flatpak. By default, the Flatpak spawns a goldwarden daemon within the sandbox. You can also use an unsandboxed daemon with the Flatpak. In this case, make sure the daemon has the following environment variable set:
`GOLDWARDEN_SOCKET_PATH=~/.var/app/com.quexten.Goldwarden/data/goldwarden.sock`

**Comment by quexten** [comment]
Yeah, the path had to be changed when publishing to FlatHub. That's why the update broke your setup, sorry about that.
