### ISSUE TITLE
Browser biometrics sometimes not asking for polkit

### ISSUE THREAD

**Issue by quexten** [quexten/goldwarden#64]
From @alba4k in https://github.com/quexten/goldwarden/issues/62#issuecomment-1891120456_

**Comment by alba4k** [comment]
Welp, I guess it is __not__ intended behaviour ahah

**Comment by quexten** [comment]
Ah, yeah, sorry about the description, it's from GitHub's "reference in new issue" feature. Updated it now.

**Comment by alba4k** [comment]
Oh, I see. No need to worry, it was perfectly fine as it was

**Comment by quexten** [comment]
Ok, so this issue is due to the fact that the daemon "caches" authentication for pid's (with an expiry time), so that repeated calls to git/ssh/etc don't require pin/biometrics every time. Obviously, for biometrics this should not happen, so that code path needs to be changed.

**Comment by quexten** [comment]
Should be fixed in fd8d483e918bd4404b2c1492812128661da732ab, but keeping it open for a while for testing

**Comment by alba4k** [comment]
Won't be home 'till Sunday. I'll let you know ASAP tho

**Comment by quexten** [comment]
@alba4k can this issue be closed?

**Comment by alba4k** [comment]
I will have to check once I get home :)
