### ISSUE TITLE
[Feature request] Add "Open web vault" button to the Goldwarden UI

### ISSUE THREAD

**Issue by MurzNN** [quexten/goldwarden#77]
Will be good to add an "Open web vault" button to the Goldwarden UI that will just open in the default browser the URL from the config with removing `/api` suffix.

And the same button for login items, which will also add the `#/vault?itemId=<uuid>` suffix to the URL with the id of the current item. Cuz pretty often I want to make changes to the item, but searching it again in the web vault is not so fun :)

**Comment by quexten** [comment]
I think the proper way to get this url is to have a web vault url in the config. While removing /api works for the official servers, it won't work for some custom setups. We can fetch all urls from an endpoint - https://vault.bitwarden.com/api/config - and thus not even have to enter api/identity url separately for custom setups.

Either way, great idea!

**Comment by quexten** [comment]
Web vault url and auto-config for urls: 8eb55f28082f7aacfe0155cabb79f3139b664dfd

**Comment by quexten** [comment]
Done in https://github.com/quexten/goldwarden/actions/runs/7594244137 , feel free to give it a try (it might require you to log out once to fix the web vault url, otherwise you can also set it via the cli).

**Comment by quexten** [comment]
Closing since this is done.
