### ISSUE TITLE
[Feature request] Move actions in the main window to the top

### ISSUE THREAD

**Issue by MurzNN** [quexten/goldwarden#78]
Now all action buttons are located at the bottom of the window, so I have to always scroll down to them.

But at the very top, I see pretty boring info that all is listening, which wastes useful space.

I think it's better to move all the Actions buttons to the top of the window, and put status and services lower.
Maybe even make status and services collapsed by default, with just displaying some "All is ok" green symbol for services and status if all is really ok, and an ability to expand it.

**Comment by quexten** [comment]
Seems reasonable. Also probably converting the "unlock" button to an adwaita banner at the top probably makes sense (that's how other apps handle this).

**Comment by quexten** [comment]
Also done in https://github.com/quexten/goldwarden/actions/runs/7594244137

**Comment by MurzNN** [comment]
Thanks for such a quick fix, much better now! But maybe also remove the "Actions" header? It's obvious that this is Actions ;)
![image](https://github.com/quexten/goldwarden/assets/336662/9ab5acde-4165-4b5a-a959-813bf4ad6c73)
