### ISSUE TITLE
Problem "TLS : internal error" - self hosting

### ISSUE THREAD

**Issue by Froggy232** [quexten/goldwarden#79]
Hi,
First, thanks you for your work!
I would like to use it with a self hosted instance of Bitwarden, but I can't connect.
When I try to, I have an error : Could not pre-login tls internal error.
I assume it's related to my ssl config?
For information, I use the default integrated let's encrypt certificate of the bitwarden docker image.
How can I retrieve it and import it to the app?
Also, what I don't understand is I can connect through Tangram, a web browser.
Thanks you,
Best regards

**Comment by quexten** [comment]
>  For information, I use the default integrated let's encrypt certificate of the bitwarden docker image.

What do you mean by "integrated" letsencrypt certificate? Usually with letsencrypt you have to verify your domain via http auth or acmev2. Did you configure the Bitwarden docker image to get a letsencrypt certificate via either of these automatically?

Just to make sure, if you open the site in your browser and don't get any SSL errors of "hey this is some untrusted certificate, are you sure you want to visit?".

Further, which distro do you use? (It could be that your browser has the letsencrypt root cert in it's store, but the golang implementation for some reason does not use the same list of root certificates).

If you run `curl https://[YOUR-BITWARDEN-INSTANCE]/`, do you get a response, or a certificate error?

**Comment by Froggy232** [comment]
Sorry, it's solved now.

**Comment by Froggy232** [comment]
Sorry, I have simply switched to vaultwarden an disabled https as I won't expose it outside the wireguard private network.
Thanks for your help!

**Comment by Froggy232** [comment]
Sorry to bother you again, but I don't understand how to use the app.
It isn't a regular password manager, it's focused on autotype?
Thanks you

**Comment by quexten** [comment]
Yes, it's not meant as a replacement for the official apps, but rather works besides it. Goldwarden adds:
- Autotype
- SSH keys
- Browser biometrics on linux
- Some other smaller things

If you just want to manage your passwords, use the web vault or the official desktop app.
