### ISSUE TITLE
Use native window decorations for the Goldwarden window on KDE

### ISSUE THREAD

**Issue by MurzNN** [quexten/goldwarden#82]
Will be good to have the option to use the native window control elements instead of custom ones. The current custom ones looks good, but not convenient to use them differently from others, habits are a sticky thing ;)
![image](https://github.com/quexten/goldwarden/assets/336662/adb19931-779a-4980-94df-b052e4fa9b85)

**Comment by quexten** [comment]
I'm not sure this is actually possible, since Wayland seems to favor client side decorations. What you note as "Native decorations" is probably just QT5 decorations, which KDE happens to use everywhere most of the time. But GTK/libadwaita apps do not use these.

**Comment by quexten** [comment]
Closing unless things change upstream on libadwaita/gtk.
