### ISSUE TITLE
Add ARM macOS builds

### ISSUE THREAD

**Issue by kothavade** [quexten/goldwarden#88]
Currently, only x86-64 builds are made for macOS. Adding release builds for aarch64 would be helpful!

**Comment by kothavade** [comment]
Perhaps relevant: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by quexten** [comment]
Yeah, I tried these a while ago, but couldn't make them work. I'm not sure if they are paid only. I might retry soon. The biggest issue is that the rest of the functionality is largely untested on Mac (since I don't have access to a mac) and some required items (pinentry) are unimplemented, so I'm not sure how useful the Mac builds currently are. At least the Wiki should specify what works and what doesn't.

**Comment by kothavade** [comment]
Makes sense, if there's anything specific you'd like tested on macOS I'm happy to help.

**Comment by quexten** [comment]
Thanks for the offer! I think the first step that would make sense here is to set up a test suite to verify basic platform-specific functionality in a quick and reliable way.

By the way, which feature(s) are you looking for specifically? Something like ssh-agent should be rather easy to do, while auto-type is more tricky (maybe with bindings to https://github.com/antelle/keyboard-auto-type).

**Comment by kothavade** [comment]
I'm primarily interested in the ssh-agent, but autofill is interesting. On macOS, though, I think it would best be implemented using the [native APIs ](https://developer.apple.com/documentation/security/password_autofill/) for autocomplete.

**Comment by quexten** [comment]
Ok, some features (pinentry) are most likely not working just yet, so for SSH agent to work there is still work to be done, but Apple silicone (aarch64) builds are now generated by the CI pipeline.

The other features are tracked in https://github.com/quexten/goldwarden/issues/4

When there are proper tests to run for the platform specific features, I'll try to ping you on that issue if that's okay.

**Comment by kothavade** [comment]
Thanks for adding aarch64 builds! Yeah, feel free to ping me if there's something you'd like tested, I'm happy to help :)
