### ISSUE TITLE
Zombie sockets left behind

### ISSUE THREAD

**Issue by lalomartins** [quexten/goldwarden#94]
Split off from https://github.com/quexten/goldwarden/issues/4#issuecomment-1924895832

Issue: if the daemon closes/crashes, sockets are left behind, and then it will refuse to start because the sockets exist.

Possibly only happens on Windows, due to the different way Windows implements sockets.

Possible workaround/fix:
- If trying to start/daemonize and the socket exists:
  - Attempt to connect to the socket and query status
  - If no response, assume zombie socket, delete, and take over

Keeping a pidfile might be an idea too, but I feel querying the socket might be simpler.

**Comment by quexten** [comment]
This is the behaviour on all platforms. But in my windows vm, the sockets get replaced on daemon restart. Still, I agree that this behaviour can be improved.

**Comment by quexten** [comment]
For Windows / SSH this should not apply anymore since we use the openssh named pipe now. (The goldwarden socket itself does still apply though).

**Comment by quexten** [comment]
Could you post the logs when the daemon "refuses to start"? Checking the code it *should* forcefully delete the existing socket, even if there is still a daemon listening there.

**Comment by lalomartins** [comment]
Would the log from 0.2.10 still be useful to you even if the code changed so much in the meantime?

I didn't really want to set up a Go dev environment to build it myself 😹 but I can if it would help.

**Comment by lalomartins** [comment]
```
~\Programs> .\goldwarden.exe daemonize
[INF] [09:30] [Goldwarden > Keyring] >>> Creating new memguard keyring
[WRN] [09:30] [Goldwarden > Agent] >>> Config is not locked. SET A PIN!!
listen error listen unix C:\Users\Lalo/.goldwarden.sock: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
panic: listen unix C:\Users\Lalo/.goldwarden-ssh-agent.sock: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

goroutine 23 [running]:
github.com/quexten/goldwarden/agent/ssh.SSHAgentServer.Serve({0xc000144000?, 0xc000104340?, 0xc00013e000?, 0xc00012a450?})
        D:/a/goldwarden/goldwarden/agent/ssh/ssh.go:198 +0x474
created by github.com/quexten/goldwarden/agent.StartUnixAgent
        D:/a/goldwarden/goldwarden/agent/unixsocketagent.go:258 +0xb93
~\Programs> ps goldwarden
Get-Process: Cannot find a process with the name "goldwarden". Verify the process name and call the cmdlet again.
```
(Adding a screenshot too for the sake of colorized output)
![image](https://github.com/quexten/goldwarden/assets/1211455/329f4f0c-6ca8-4700-876f-b28be3b0a544)

In contrast, this is what it looks like if I delete the sockets:
![image](https://github.com/quexten/goldwarden/assets/1211455/10b6c3a9-7db5-42ee-bfa3-97d5e6a85d77)

Worth of note: I haven't actually tried to run Goldwarden today before taking the first screenshot, so possibly the zombie sockets survived even a system reboot? I'll test later and let you know.

After running it successfully (second screenshot), stopping it with ctrl-C still leaves the sockets behind. Trying to run it again after that goes back to the top of the loop.

**Comment by quexten** [comment]
Possibly fixed in:
https://github.com/quexten/goldwarden/actions/runs/7770571485

**Comment by quexten** [comment]
> I didn't really want to set up a Go dev environment to build it myself 😹 but I can if it would help.

You can download the binary from the github ci actions, no need to set up a dev environment.

**Comment by quexten** [comment]
To even log in at all, you need a newer version than you are running (such as the one I linked above), and install GPG4Win (https://gpg4win.org/download.html) to get the pinentry working.

**Comment by lalomartins** [comment]
Got it, I'll give it a shot. Already have GPG4Win here.

**Comment by lalomartins** [comment]
```
~\Programs> .\goldwarden.exe daemonize
[INF] [10:10] [Goldwarden > Keyring] >>> Creating new memguard keyring
[WRN] [10:10] [Goldwarden > Agent] >>> Config is not locked. SET A PIN!!
[FATAL] [10:10] [Goldwarden > SSH] >>> listen error:%!(EXTRA *fs.PathError=open \\.\pipe\openssh-ssh-agent: Access is denied.)
```
![image](https://github.com/quexten/goldwarden/assets/1211455/53df0184-1fcc-470c-a8b3-cccd6e1ee2c7)
I'm not sure about that pipe path. Maybe it's looking for an env variable I don't have? Should I have openssh agent running or stopped?

**Comment by quexten** [comment]
The openssh agent should be stopped in services.msc.

**Comment by lalomartins** [comment]
Ok. The service is stopped (it has been for a while, as I was using 1password's). I also stopped 1password's agent, but no change. For science, I even quit 1password completely, but still no go.

The path is correct? Where is it trying to create the pipe? “Access is denied” might indicate it's trying to create it somewhere my user doesn't have write permission, which is something that could conceivably be different between my setup and your test VM.

**Comment by quexten** [comment]
Hmm, so my VM is a fresh Windows 10 Home install. The socket is from the 1Password docs, and works (at least in my VM): 
![image](https://github.com/quexten/goldwarden/assets/11866552/5b0eed13-f966-4d31-8488-2eed5b4d3fec)

**Comment by lalomartins** [comment]
Hm. I think I found the issue. I had OpenSSH on “manual” instead of “disabled”, and something was starting it 🤔 with that out of the way, Goldwarden could start, set pin, and log in.

More importantly, closing it and running it again worked fine, so I can confirm this bug is fixed on Windows. 🎉

**Comment by quexten** [comment]
Thanks for testing!
