### ISSUE TITLE
Make SSH Signage permissions configurable

### ISSUE THREAD

**Issue by quexten** [quexten/goldwarden#97]
### Discussed in https://github.com/quexten/goldwarden/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **benni347** February  5, 2024</sup>
Hey, I wanted to ask if it is possible to deactivate the window which asks to allow ssh signage, if it is possible, I would also like to know if I can activate/deactivate it on a per app basis?

I am talking about these windows:
![20240205_09h48m38s_grim](https://github.com/quexten/goldwarden/assets/64905406/0f71eb4a-dd26-42af-b638-08f41fdad16f)
![20240205_09h48m47s_grim](https://github.com/quexten/goldwarden/assets/64905406/1a80f7ab-c841-48de-a617-d4a23e18ae03)
</div>

**Comment by quexten** [comment]
SSH key prompts should rarely occur now, doing even less would lower the security.

**Comment by jaypikay** [comment]
Hi, I still have it for every single ssh connection.
